version: '3'

services:
  db:
    container_name: pg_database
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
        - '5432:5432'
    volumes:
        - postgres13:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:7.0.15-alpine
    ports:
    - '6379:6379'
    volumes:
    - redis_data:/data
  web: &web
    container_name: rails_web_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/rails
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_test
      - REDIS_URL=redis://redis:6379/0
  test:
    <<: *web
    container_name: test
    command: bundle exec rspec
    profiles: [test]

  sidekiq:
    container_name: sidekiq
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    command: bundle exec sidekiq -q default
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp_test
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
    postgres13:
    redis_data:
